name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    uses: singi0771/ci-standards/.github/workflows/ci-reusable.yml@v1.1.0
    with:
      python-version: "3.9"
      run-docker-build: false
      run-python: true
      run-actionlint: true
      run-shellcheck: true
